/*
 * ModemConnection.h
 *
 * Created: 5/22/2018 12:51:22 PM
 *  Author: anilj
 */ 


#ifndef MODEMCONNECTION_H_
#define MODEMCONNECTION_H_

#include "Apps/SerialDebug/SerialDebug.h"

/* Main states for Modem Connection */
typedef enum
{
	MDM_HTTP_DISCONNECTED,
	MDM_HTTP_CONNECTION_IN_PROGRESS,
	MDM_HTTP_CONNECTED,
	MDM_HTTP_DISCONNECTION_IN_PROGRESS,
	MDM_HTTP_CONNECTION_FAULT
}HTTP_CONNECT_STATES_T;

/* MDM_HTTP_CONNECTION_IN_PROGRESS sub-states */
typedef enum
{
	CONNECT_IN_PROGRESS_CLOSE_CONNECTION,
	CONNECT_IN_PROGRESS_SET_EOF_PATTERN,
	CONNECT_IN_PROGRESS_SET_ACCESS_POINT,
	CONNECT_IN_PROGRESS_SET_CONNECT_TIMERS,
	CONNECT_IN_PROGRESS_SET_SERVER_ADDRESS,
	CONNECT_IN_PROGRESS_SET_HTTP_HEADER
}HTTP_CONNECT_IN_PROGRESS_SUBSTATES_T;

typedef enum
{
	HTTP_CONNECT_OP_TX_MODE,
	HTTP_CONNECT_OP_RX_MODE,
	HTTP_CONNECT_OP_MAX_MODE
}HTTP_CONNECT_OPERATIONAL_STATE_T;

typedef enum
{
	GET_TOTAL_NO_OF_ACTIVE_CONNECTIONS,
	CLOSE_ALL_EXISTING_CONNECIONS
}HTTP_CLOSE_CONNECTIONS_STATE_T;

#define MAX_ACTIVE_SESSION_ID     (10)
#define SESSION_ID_POSITION       (11)
#define SESSION_ID_POS_IN_HEADER  (15)
#define SESSION_ID_POS_IN_GET_REQ (12)

void MdmCnct_ConnectInProgressSubStateMachine(void);
void MdmConnect_HttpConnectionSchedule(void);
void MdmConnect_HttpConnectionInit(void);

#endif /* MODEMCONNECTION_H_ */
