/*
 * ModemConnectionConfig.h
 *
 * Created: 5/22/2018 7:31:34 PM
 *  Author: anilj
 */ 


#ifndef MODEMCONNECTIONCONFIG_H_
#define MODEMCONNECTIONCONFIG_H_

/* Define the Access Point Name */
#define MODEM_APN "VZWINTERNET"

/* Define the Server Name */
#define HTTP_SERVER "ingest1.response.cloud"

/* PDP CONNECTION STATUS reported from Modem */
typedef enum
{
	PDP_DISCONNECTED_DUE_TO_NETWORK,
	PDP_CONNECTED,
	PDP_FAILED_TO_CONNECT,
	PDP_CLOSED,
	PDP_CONNECTION_IN_PROGRESS,
	PDP_IDLE_TIMER_STARTED,
	PDP_IDLE_TIMER_CANCELLED
}PDP_CONNECTION_STATUS;

/* Session ID for PDP connection */
typedef enum
{
	PDP_SESSION_ID_1,
	PDP_SESSION_ID_2,
	PDP_SESSION_ID_3,
	PDP_SESSION_ID_4,
	PDP_SESSION_ID_5,
	PDP_SESSION_ID_6,
	PDP_SESSION_ID_7,
	PDP_SESSION_ID_8,
	PDP_SESSION_ID_9,
	PDP_SESSION_ID_10,
	PDP_SESSION_ID_11,
	PDP_SESSION_ID_12,
	PDP_SESSION_ID_13,
	PDP_SESSION_ID_14,
	PDP_SESSION_ID_15,
	PDP_SESSION_ID_16,
	PDP_SESSION_ID_17,
	PDP_SESSION_ID_18,
	PDP_SESSION_ID_19,
	PDP_SESSION_ID_20,
	PDP_SESSION_ID_21,
	PDP_SESSION_ID_22,
	PDP_SESSION_ID_23,
	PDP_SESSION_ID_24,
	PDP_SESSION_ID_25,
	PDP_SESSION_ID_26,
	PDP_SESSION_ID_27,
	PDP_SESSION_ID_28,
	PDP_SESSION_ID_29,
	PDP_SESSION_ID_30,
	PDP_SESSION_ID_31,
	PDP_SESSION_ID_32
}PDP_SESSION_ID;

/* PDP Context Configuration */
#define PDP_CONTEXT_CONFIG_1 (1)
#define PDP_CONTEXT_CONFIG_2 (2)
#define PDP_CONTEXT_CONFIG_3 (3)
#define PDP_CONTEXT_CONFIG_4 (4)
#define PDP_CONTEXT_CONFIG_5 (5)

/* PDP Connection Parameters */
#define PDP_CONNECTION_RETRY_TIMEOUT (60)
#define PPD_CONNECTION_MAX_RETRY_COUNT (2)
#define PDP_CONNECTION_MIN_TIMEOUT (70)
#define PDP_CONNECTION_IDLE_TIMEOUT (60)
#define DEFAULT_EOF_PATTERN "--EOF--Pattern--"




#endif /* MODEMCONNECTIONCONFIG_H_ */