/*
 * ModemConnection.h
 *
 * Created: 5/22/2018 12:51:22 PM
 *  Author: anilj
 */ 


#ifndef MODEMCONNECTION_H_
#define MODEMCONNECTION_H_

#include "Apps/SerialDebug/SerialDebug.h"

/* Main states for Modem Connection */
typedef enum
{
	MDM_HTTP_DISCONNECTED,
	MDM_HTTP_CONNECTION_IN_PROGRESS,
	MDM_HTTP_CONNECTED,
	MDM_HTTP_DISCONNECTION_IN_PROGRESS,
	MDM_HTTP_CONNECTION_FAULT
}HTTP_CONNECT_STATES_T;

/* MDM_HTTP_CONNECTION_IN_PROGRESS sub-states */
typedef enum
{
	CONNECT_IN_PROGRESS_CLOSE_CONNECTION,
	CONNECT_IN_PROGRESS_SET_EOF_PATTERN,
	CONNECT_IN_PROGRESS_SET_ACCESS_POINT,
	CONNECT_IN_PROGRESS_SET_CONNECT_TIMERS,
	CONNECT_IN_PROGRESS_SET_SERVER_ADDRESS,
	CONNECT_IN_PROGRESS_SET_HTTP_HEADER
}HTTP_CONNECT_IN_PROGRESS_SUBSTATES_T;

#define MAX_ACTIVE_SESSION_ID (10)

void MdmCnct_ConnectInProgressSubStateMachine(void);
void MdmCnct_HttpConnectionStateMachine(void);


#endif /* MODEMCONNECTION_H_ */
